package(default_visibility = ["//visibility:public"])

cc_library(
	name = "io",
	hdrs = ["io.h"],
	srcs = ["io.cpp"],
	deps = [
		"//ie_solver:ie_mat",
		"//ie_solver:log",
		"//ie_solver/boundaries",
		"//ie_solver/quadtree",
	],
)
