package(default_visibility = ["//visibility:public"])


cc_library(
	name = "kernel",
	hdrs = ["kernel.h"],
	srcs = ["kernel.cpp"],
	deps = ["//ie_solver:ie_mat",
          "//ie_solver/boundaries",
          "//ie_solver/io",
					"//ie_solver/quadtree"]
)
