package(default_visibility = ["//visibility:public"])

cc_library(
  name = "quadtree",
  hdrs = ["quadtree.h"],
  srcs = ["quadtree.cpp",
        ],
  deps = ["//ie_solver:ie_mat",
      "//ie_solver/boundaries"]
)